### ISSUE TITLE
error when starting mock server

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/karma-pact#6]
Currently, when I'm trying to start a mock server in a karma test run, I get the following error:

```
Unhandled rejection TypeError: Cannot read property 'port' of undefined
    at C:\daten\workspaces\code-examples\angular-pact\node_modules\@pact-foundation\karma-pact\src\index.js:19:66
```

Looking into the issue, I found that the following line in `index.js` is the culprit:

```
log.info('Pact Mock Server running on port: ' + server.options.port);
```

I found out that the `server` object does not have an attribute named `options` but rather one named `_options`. If I change it to `_options` everything works fine. 

I don't know where the error now comes from, since it worked a couple weeks ago.

I use these versions:
```
pact-node: 5.1.2
karma-pact: 2.1.0
```

**Comment by mboudreau** [comment]
@thombergs are you sure you've done an npm update recently?  pact-node has had it's `options` variable renamed in 5, from _options to options as to make it publicly available.

**Comment by blackbaud-joshlandi** [comment]
I encountered this too.  You can try _not_ marking `pact-node` as a dependency and simply letting the dependencies of  `karma-pacts` take care of importing the necessary version.  Having it specified at your app level seems to overwrite child dependencies.  I've got karma-pact, pact, and pact-web in my dependencies, all getting the latest version and it works fine.

If it is indeed the case that we shouldn't specify a pact-node dependency in our own package.json, since it overrides karma-pact's dependency version, maybe that could be documented somewhere?

**Comment by mefellows** [comment]
It's a good point. Unless your writing a library, there is generally no need to import pact-node directly. I'm confused through any docs that suggest otherwise

**Comment by isayneigh** [comment]
For my team at least, when we started using your packages months ago we were pretty new to it and we erroneously had it in out dependencies.  It didn't appear to affect anything so it sort of just stayed while in our tests we were really only using your `pact-js` package.  Working with `karma-pact` during the ongoing update to Typescript has exposed the issue with having `pact-node` as an app level dependency.

I don't think any @pact-foundation docs suggest importing pact-node, but it's a possible mistake that could me noted in a FAQs section.  Just a suggestion, otherwise this really is a non issue.

**Comment by mboudreau** [comment]
hm, this is interesting.  karma-pact, since 2.X has used pact-node as a peer dependency since it was normally needed anyways at the base level project, but it still specifies the minimum version needed to be used.

Not sure how this is being caused frankly, because the peer dependency is for pact-node ^5.1.2, which would have the public options property.

@thombergs if you can give me an example to work with, that would be great.

**Comment by thombergs** [comment]
Sorry for the late reply, I was unavailable last week (fittingly, I was on a conference talking about CDC...).

Actually, in my `package.json` I had pact-node listed in version 4. The information in the original issue above was from my package-lock.json. When I list pact-node 5 in `package.json` everything works.

However, when I leave pact-node completely out of my `package.json` (expecting npm to resolve the dependency from `karma-pact` to `pact-node` itself), I get the following error when running a karma test:

```
13 11 2017 23:14:15.114:ERROR [config]: Error in config file!
 { Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\daten\workspaces\code-examples2\angular-pact\node_modules\@pact-foundation\pact-node\src\pact.ts:1:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\daten\workspaces\code-examples2\angular-pact\node_modules\@pact-foundation\pact-node\src\index.ts:1:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-pact@0.0.0 test: `cross-env LOGLEVEL=DEBUG ng test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-pact@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

You can reproduce this with my example at https://github.com/thombergs/code-examples/tree/master/angular-pact by following these steps:

* delete dependency to `@pact-foundation/pact-node` from `package.json`
* delete `package-lock.json`
* run `npm install`
* run `npm run test`

**Comment by mboudreau** [comment]
@thombergs like I said, since version 5, karma-pact doesn't have a straight dependency to pact-node; it's now a peer dependency.  The idea is that the developer should be able to use the latest pact-node that matches the version criteria without us needing to update karma-pact.

This should have been apparent when you tried to do an `npm install` and it would say "unmet peer dependency" or something along those lines.  From now on, when installing karma-pact, pact-node must be installed as well.

I forgot to update the readme in karma-pact, doing that now.
